#!/bin/sh
yq -Yi '(.spec.params[] | select(.name == "GIT_REPO").value) |="https://github.com/maximilianoPizarro/jhipster-demo-artifcat"' pipeline-run.yaml
yq -Yi '(.spec.params[] | select(.name == "APP_JAR_VERSION").value) |="jhipster-demo-artifcat-1.0.0-SNAPSHOT-runner.jar"' pipeline-run.yaml
